-- Drop the tables with foreign key references first
DROP TABLE IF EXISTS WORKS_ON;

DROP TABLE IF EXISTS BUILDS;

DROP TABLE IF EXISTS EPHONE;

DROP TABLE IF EXISTS PRICE_HISTORY;

-- Drop the remaining tables
DROP TABLE IF EXISTS EMPLOYEE;

DROP TABLE IF EXISTS PRODUCT;

DROP TABLE IF EXISTS PROJECT;

DROP TABLE IF EXISTS DEPARTMENT;